# Generated by Django 5.1.2 on 2025-02-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_auth', '0002_alter_registermodel_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
