# Generated by Django 5.1.2 on 2025-02-03 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_auth', '0003_registermodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshTokenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('Token', models.CharField(max_length=255, unique=True)),
                ('expired_at', models.DateField()),
                ('revoked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Refresh_Token', to='login_auth.registermodel')),
            ],
        ),
    ]
